//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebNoiThatReal.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Customer
    {
        public Customer()
        {
            this.OrderProes = new HashSet<OrderPro>();
        }

        public int IDCus { get; set; }

        [Required(ErrorMessage = "*")]
        [DisplayName("Tên đăng nhập")]
        public string UserNameCus { get; set; }

        [Required(ErrorMessage = "*")]
        [DisplayName("Họ và Tên")]
        public string NameCus { get; set; }

        [Required(ErrorMessage = "*")]
        [DisplayName("Mật khẩu")]
        public string PasswordCus { get; set; }

        [Required(ErrorMessage = "*")]
        [NotMapped]
        [Compare("PasswordCus", ErrorMessage = "!!")]
        [DisplayName("Nhập lại mật khẩu")]
        public string ConfirmPass { get; set; }


        [Required(ErrorMessage = "*")]
        [DisplayName("Số điện thoại")]
        public string PhoneCus { get; set; }
        [DisplayName("Email")]
        public string EmailCus { get; set; }


        [NotMapped]
        public string ErrorTV { get; set; }

        public virtual ICollection<OrderPro> OrderProes { get; set; }
    }
}
