//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebNoiThatReal.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;

    public partial class Event
    {

        public Event()
        {

            ImageUrl = "~/Content/Images/hinhsp/add.jpg";
        }
        public int Id { get; set; }
        public string EventName { get; set; }
        public string Title { get; set; }
        public System.DateTime EventDate { get; set; }
        public Nullable<int> Views { get; set; }
        public string Description { get; set; }
        public string ImageUrl { get; set; }

        [NotMapped]
        public HttpPostedFileBase UploadImage { get; set; }
    }
}
